name = "lilhash"
type = "webpack"

account_id = ""
workers_dev = false
route = "lilhash.com/*"
zone_id = ""
compatibility_date = "2021-10-05"
kv_namespaces = [
  { binding = "KV", id = "SECRET", preview_id = "SECRET" }
]